version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
      
  - package-ecosystem: "github-actions"
    directory: "/"
    schedle:
      interval: "monthly"
    open-pull-requests-limit: 1
